source 'https://rubygems.org'
#gem 'igraph', '0.9.7'
gem 'sidekiq', '3.2.1'
gem 'nokogiri'
gem 'pry'
gem 'mongo_mapper', '0.12.0'
gem 'bson_ext'
gem 'rake', '0.9.2'
gem 'redis'
gem 'sinatra'
gem 'rest_client'
gem 'twitter-text'
gem 'twitter'
